name: CI/CD Pipeline

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ staging ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY_BACKEND: ${{ secrets.ECR_REGISTRY_BACKEND }}
      ECR_REGISTRY_FRONTEND: ${{ secrets.ECR_REGISTRY_FRONTEND }}
      ECR_REGISTRY_NO: ${{ secrets.ECR_REGISTRY_NO }}

    services:
      docker:
        image: docker:20.10.7-dind

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get lowercase repo
        id: repo
        run: echo "repo=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Get workload SHA
        id: workload_sha
        run: echo "workload_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Check if frontend workload changed
        id: frontend-workload-changed
        run: |
          # If this is the first commit on a branch
          if [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ] || [ -z "${{ github.event.before }}" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files:"
          echo "$CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -E "^ClientSide/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if backend workload changed
        id: backend-workload-changed
        run: |
          # If this is the first commit on a branch
          if [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ] || [ -z "${{ github.event.before }}" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files:"
          echo "$CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -E "^ServerSide/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Log in to ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "$ECR_REGISTRY_NO".dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push workload Frontend Docker image 
        if: steps.frontend-workload-changed.outputs.changed == 'true'
        run: |
          cd ClientSide
          TAG=${{ steps.workload_sha.outputs.workload_sha }}-staging
          docker build -t $ECR_REGISTRY_NO.dkr.ecr.us-east-1.amazonaws.com/$ECR_REGISTRY_FRONTEND:$TAG .
          docker push $ECR_REGISTRY_NO.dkr.ecr.us-east-1.amazonaws.com/$ECR_REGISTRY_FRONTEND:$TAG
          echo "FRONTEND_NEW_IMAGE=$ECR_REGISTRY_NO.dkr.ecr.us-east-1.amazonaws.com/$ECR_REGISTRY_FRONTEND:$TAG" >> $GITHUB_ENV

      - name: Build and Push workload Backend Docker image
        if: steps.backend-workload-changed.outputs.changed == 'true'
        run: |
          cd ServerSide
          TAG=${{ steps.workload_sha.outputs.workload_sha }}-staging
          docker build -t $ECR_REGISTRY_NO.dkr.ecr.us-east-1.amazonaws.com/$ECR_REGISTRY_BACKEND:$TAG .
          docker push $ECR_REGISTRY_NO.dkr.ecr.us-east-1.amazonaws.com/$ECR_REGISTRY_BACKEND:$TAG
          echo "BACKEND_NEW_IMAGE=$ECR_REGISTRY_NO.dkr.ecr.us-east-1.amazonaws.com/$ECR_REGISTRY_BACKEND:$TAG" >> $GITHUB_ENV

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          
      - name: setup git and clone brew formula
        uses: actions/checkout@v3
        with:
          path: 'Argo-GitOps'
          ref: 'staging'
          repository: 'prakrit55/Argo-GitOps'
          token: ${{ secrets.GHCR_PAT }}
          fetch-depth: 0
          persist-credentials: true

      - name: Update workload image name in Backend Manifest
        if: steps.backend-workload-changed.outputs.changed == 'true'
        run: |
          cd Argo-GitOps
          git checkout -b staging-${{ github.run_number }}
          yq -i '.spec.template.spec.containers[0].image = env(BACKEND_NEW_IMAGE)' backend/backend.yaml

      - name: Update workload image in Frontend Manifest
        if: steps.frontend-workload-changed.outputs.changed == 'true'
        run: |
          cd Argo-GitOps
          git checkout staging-${{ github.run_number }}
          yq -i '.spec.template.spec.containers[0].image = env(FRONTEND_NEW_IMAGE)' frontend/frontend.yaml

      - name: Commit changes
        if: steps.backend-workload-changed.outputs.changed == 'true' || steps.frontend-workload-changed.outputs.changed == 'true'
        run: |
          cd Argo-GitOps
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Update image"
          git push --set-upstream origin HEAD

      - name: Create Pull Request on Argo-GitOps
        if: steps.backend-workload-changed.outputs.changed == 'true' || steps.frontend-workload-changed.outputs.changed == 'true'
        env:
          GH_PAT: ${{ secrets.GHCR_PAT }}
        run: |
          BRANCH="staging-${{ github.run_number }}"

          curl --fail-with-body \
            -X POST https://api.github.com/repos/prakrit55/Argo-GitOps/pulls \
            -H "Authorization: Bearer $GH_PAT" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -d "{\"title\": \"Update deployment manifests\", \"head\": \"$BRANCH\", \"base\": \"staging\", \"body\": \"Automated update from GitHub Actions\"}"
